#!/bin/env bash

# Read expression
read -r a op b

case "$op" in
  +) echo $((a + b)) ;;
  -) echo $((a - b)) ;;
  \*) echo $((a * b)) ;;
  /) echo $((a / b)) ;;
  %) echo $((a % b)) ;;
  *) echo "Operator tidak valid" ;;
esac
